version: "3"
services:
    redis:
        image: "redis"
        ports:
            - "6000:6379"
        networks:
            - backend

    api:
        image: paytm-saravanan
        build: .
        networks:
            - backend
        ports:
            - "5050:5000"
        depends_on:
            - redis
        links:
            - "redis"
        environment:
            redis_host: "redis"
            node_env: "prod"

networks:
    backend:
        driver: bridge
